---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-endeca-mdex
      transport: "web"
      mdex_version: "11.3.0"
      transport_web: "{{ lookup('env','STORAGE_AWS') }}/oracle-commerce-suite/commerce/endeca11.3.0/V861206-01.zip"
